export const genresMap = {
  Action: "action",
  Adaptation: "adaptation",
  Adult: "adult",
  Adventure: "adventure",
  Animal: "animal",
  Anthology: "anthology",
  Cartoon: "cartoon",
  Comedy: "comedy",
  Comic: "comic",
  Cooking: "cooking",
  Demons: "demons",
  Doujinshi: "doujinshi",
  Drama: "drama",
  Ecchi: "ecchi",
  Fantasy: "fantasy",
  FullColor: "full-color",
  Game: "game",
  GenderBender: "gender-bender",
  Ghosts: "ghosts",
  Harem: "harem",
  Historical: "historical",
  Horror: "horror",
  Isekai: "isekai",
  Josei: "josei",
  LongStrip: "long-strip",
  Mafia: "mafia",
  Magic: "magic",
  Manga: "manga",
  Manhua: "manhua",
  Manhwa: "manhwa",
  MartialArts: "martial-arts",
  Mature: "mature",
  Mecha: "mecha",
  Medical: "medical",
  Military: "military",
  Monster: "monster",
  MonsterGirls: "monster-girls",
  Monsters: "monsters",
  Music: "music",
  Mystery: "mystery",
  Office: "office",
  OfficeWorkers: "office-workers",
  OneShot: "one-shot",
  Police: "police",
  Psychological: "psychological",
  Reincarnation: "reincarnation",
  Romance: "romance",
  SchoolLife: "school-life",
  SciFi: "sci-fi",
  ScienceFiction: "science-fiction",
  Seinen: "seinen",
  Shoujo: "shoujo",
  ShoujoAi: "shoujo-ai",
  Shounen: "shounen",
  ShounenAi: "shounen-ai",
  SliceOfLife: "slice-of-life",
  Smut: "smut",
  SoftYaoi: "soft-yaoi",
  Sports: "sports",
  SuperPower: "super-power",
  Superhero: "superhero",
  Supernatural: "supernatural",
  Thriller: "thriller",
  TimeTravel: "time-travel",
  Tragedy: "tragedy",
  Vampire: "vampire",
  Vampires: "vampiers",
  VideoGames: "video-games",
  Villainess: "villainess",
  WebComic: "web-comic",
  Webtoons: "webtoons",
  Yaoi: "yaoi",
  Yuri: "yuri",
  Zombies: "zombies",
} as const;
export type MANGABUDDY_GENRES = keyof typeof genresMap;

export const genreSortMap = {
  TopDay: "top-day",
  TopWeek: "top-week",
  TopMonth: "top-month",
  Views: "views",
  Updated: "updated_date",
  Created: "created_date",
} as const;

export type MANGABUDDY_GENRE_SORT = keyof typeof genreSortMap;

export const genreStatusMap = {
  All: "all",
  Ongoing: "ongoing",
  Completed: "completed",
};

export type MANGABUDDY_GENRE_STATUS = keyof typeof genreStatusMap;
